/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablerCheck: typeof import('~icons/tabler/check')['default']
    TablerCopy: typeof import('~icons/tabler/copy')['default']
    TablerDownload: typeof import('~icons/tabler/download')['default']
  }
}
