/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TablerCheck: typeof import('~icons/tabler/check')['default']
    TablerCopy: typeof import('~icons/tabler/copy')['default']
    TablerDownload: typeof import('~icons/tabler/download')['default']
    VueGroupCode: typeof import('./src/components/VueGroupCode.vue')['default']
    VueMarkDownHeader: typeof import('./src/components/VueMarkDownHeader.vue')['default']
    VueMarkdownIt: typeof import('./src/components/VueMarkdownIt.vue')['default']
    VueMarkdownItProvider: typeof import('./src/components/VueMarkdownItProvider.vue')['default']
  }
}
